name: brew audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup tap
        uses: ./.github/actions/setup-tap

      - name: Audit formulae
        run: brew audit --formula --tap zeroc-ice/tap --online --strict --git

      - name: Audit casks
        run: brew audit --cask --tap zeroc-ice/tap --online --strict --git
