name: brew audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup tap
        uses: ./.github/actions/setup-tap

      - name: Audit formulae
        run: brew audit --formula --tap zeroc-ice/tap --online --strict --git

      - name: Audit casks
        run: brew audit --cask --tap zeroc-ice/tap --online --strict --git
